# Generated by Django 5.2.5 on 2025-08-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('step', models.CharField(choices=[('title', 'タイトル入力待ち'), ('start', '開始日時入力待ち'), ('end', '終了日時入力待ち'), ('cap', '定員入力待ち'), ('done', '完了')], default='title', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
