# Generated by Django 5.2.5 on 2025-08-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
