# Generated by Django 5.2.5 on 2025-08-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdraft',
            name='step',
            field=models.CharField(choices=[('title', 'タイトル入力待ち'), ('start', '開始日時入力待ち'), ('end_mode', '終了指定方法の選択待ち'), ('end', '終了日時入力待ち'), ('duration', '所要時間入力待ち'), ('cap', '定員入力待ち'), ('done', '完了')], default='title', max_length=10),
        ),
    ]
