# Generated by Django 5.2.5 on 2025-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventdraft_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdraft',
            name='step',
            field=models.CharField(choices=[('title', 'タイトル入力待ち'), ('start_date', '開始日入力待ち'), ('start_time', '開始時刻入力待ち'), ('end_mode', '終了指定方法の選択待ち'), ('end_date', '終了日入力待ち'), ('end_time', '終了時刻入力待ち'), ('duration', '所要時間入力待ち'), ('cap', '定員入力待ち'), ('done', '完了')], default='title', max_length=10),
        ),
    ]
