# Generated by Django 5.2.5 on 2025-09-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdraft',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='start_time_has_clock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='start_time_has_clock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventdraft',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventdraft',
            name='step',
            field=models.CharField(choices=[('title', 'タイトル入力待ち'), ('start_date', '開始日入力待ち'), ('start_time', '開始時刻入力待ち'), ('end_mode', '終了指定方法の選択待ち'), ('end_time', '終了時刻入力待ち'), ('duration', '所要時間入力待ち'), ('cap', '定員入力待ち'), ('done', '完了')], default='title', max_length=10),
        ),
    ]
