# Generated by Django 5.2.5 on 2025-09-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventdraft_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdraft',
            name='end_time_has_clock',
            field=models.BooleanField(default=False, help_text='終了時刻が HH:MM で指定された場合に True'),
        ),
    ]
