# Generated by Django 5.2.5 on 2025-09-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventdraft_end_time_has_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
