# Generated by Django 5.2.5 on 2025-09-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEditDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('step', models.CharField(choices=[('menu', '編集項目メニュー表示中'), ('title', 'タイトル編集中'), ('start_date', '開始日編集中'), ('start_time', '開始時刻編集中'), ('end_mode', '終了指定方法選択中'), ('end_time', '終了時刻編集中'), ('duration', '所要時間編集中'), ('cap', '定員編集中'), ('confirm', '確認')], default='menu', max_length=12)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('start_time_has_clock', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('end_time_has_clock', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_drafts', to='events.event')),
            ],
        ),
    ]
