# Generated by Django 5.2.5 on 2025-09-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventeditdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scope_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='scope_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eventeditdraft',
            name='scope_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
