# Generated by Django 5.2.5 on 2025-09-10 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_scope_id_eventdraft_scope_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('picture_url', models.TextField(blank=True, default='')),
                ('joined', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_summary_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
